### ISSUE TITLE
关于按键的问题

### ISSUE THREAD

**Issue by ImMrMa** [genokolar/notes#11]
请问这个切换到usb模式下，支持全键无冲吗

**Comment by ImMrMa** [comment]
有没有兴趣合作做一把键盘，我可以设计外观，电路布线，焊接等等

**Comment by genokolar** [comment]
不支持全键无冲，只支持6键无冲。
你可以联系原作者JIM。最近蓝牙5.0的键盘快成熟了。

**Comment by ImMrMa** [comment]
是因为代码的原因还是硬件的原因呢，我向自己做一款键盘，发现你们其他方面都具备了，只有全键无冲这块的问题，另外5.0我看是你在做啊，5.0能支持全键无冲，能向下兼容吗

**Comment by genokolar** [comment]
代码问题。自己做键盘参考代码修改就行。
